# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'Fashion', b'Fashion'), (b'Watches', b'Watches'), (b'Fine Jewelry', b'Fine Jewelry'), (b'Fashion Jewelry', b'Fashion Jewelry'), (b'Engagement & Wedding', b'Engagement & Wedding'), (b"Men's Jewelry", b"Men's Jewelry"), (b'Vintage & Antique', b'Vintage & Antique'), (b'Loose Diamonds', b'Loose Diamonds'), (b'Loose Beads', b'Loose Beads')], default=b'Fashion', max_length=25),
        ),
    ]
