# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('usage', models.CharField(max_length=20)),
                ('sport', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('product_logo', models.FileField(blank=True, upload_to=b'product_images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_avatar', models.FileField(blank=True, upload_to=b'user_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
