# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'Taras', b'Trs'), (b'Iruna', b'Irn')], default=b'Andrew', max_length=20),
        ),
    ]
