# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20161021_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sport',
            new_name='like',
        ),
    ]
