# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20161125_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rango.Category'),
        ),
    ]
