# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20161129_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_logo',
            new_name='productLogo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_logo',
            new_name='userLogo',
        ),
    ]
