# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Number')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Number'),
        ),
        migrations.AddField(
            model_name='age',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Number'),
        ),
    ]
