# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_auto_20170203_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='number',
            new_name='numbers',
        ),
        migrations.AddField(
            model_name='city',
            name='html_href',
            field=models.CharField(default='tars', max_length=40),
            preserve_default=False,
        ),
    ]
