# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_auto_20170203_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
