# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_auto_20170203_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='age',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
