# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_auto_20170203_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='html_href',
            field=models.CharField(max_length=60),
        ),
    ]
