# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_auto_20170203_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='numbers',
        ),
        migrations.AddField(
            model_name='number',
            name='cities',
            field=models.ManyToManyField(to='bingo.City'),
        ),
    ]
