# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_auto_20170204_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='age',
            name='number',
        ),
        migrations.AddField(
            model_name='number',
            name='ages',
            field=models.ManyToManyField(to='bingo.Age'),
        ),
        migrations.AddField(
            model_name='number',
            name='images',
            field=models.ManyToManyField(to='bingo.Images'),
        ),
    ]
