# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_auto_20170204_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
