# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_remove_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='format',
            field=models.CharField(default='jpg', max_length=10),
            preserve_default=False,
        ),
    ]
