# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0012_images_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='format',
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=32, max_length=15),
            preserve_default=False,
        ),
    ]
