# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0013_auto_20170207_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(default=3),
            preserve_default=False,
        ),
    ]
