# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0014_auto_20170209_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={},
        ),
    ]
