# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0015_auto_20170209_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 19, 14, 37, 773034)),
        ),
    ]
