# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0017_auto_20170209_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
