# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0019_auto_20170209_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
