# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0021_remove_images_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 17, 28, 0, 690186, tzinfo=utc)),
        ),
    ]
