# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0022_auto_20170209_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 17, 29, 6, 385844, tzinfo=utc)),
        ),
    ]
