# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0026_auto_20170209_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedate',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
